name: Tests

on: pull_request

jobs:
    gut:
        name: Godot Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Run GUT Tests
              uses: josephbmanley/run-gut-tests-action@v1.0.1
              env:
                DEFAULT_BRANCH: master

